name: Program Code Linter

on:
  push:
    paths:
      - "**/*.cs"
  pull_request:

jobs:
  ProgramCodeLinter:
    name: ProgramCodeLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_CSHARP: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
